version: '3'
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - fastapi
    restart: always
